#=========================================================================
# OpenRAM SRAM Compiler 
#=========================================================================
# Author : Kartik Prabhu
# Date   : February 15, 2020
#

name: sram

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------

outputs:
  - sram_1kbyte_1rw1r_32x256.sp
  - sram_1kbyte_1rw1r_32x256.v
  - sram_1kbyte_1rw1r_32x256.lef
  - sram_1kbyte_1rw1r_32x256_tt_1p8V_25C.lib
  - sram_1kbyte_1rw1r_32x256_tt_1p8V_25C.db
  - sram_1kbyte_1rw1r_32x256.gds

  - sram_2kbyte_1rw1r_32x512.sp
  - sram_2kbyte_1rw1r_32x512.v
  - sram_2kbyte_1rw1r_32x512.lef
  - sram_2kbyte_1rw1r_32x512_tt_1p8V_25C.lib
  - sram_2kbyte_1rw1r_32x512_tt_1p8V_25C.db
  - sram_2kbyte_1rw1r_32x512.gds

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.sp              outputs/sram_1kbyte_1rw1r_32x256.sp
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.v               outputs/sram_1kbyte_1rw1r_32x256.v
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.lef             outputs/sram_1kbyte_1rw1r_32x256.lef
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib outputs/sram_1kbyte_1rw1r_32x256_tt_1p8V_25C.lib
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.gds             outputs/sram_1kbyte_1rw1r_32x256.gds
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db  outputs/sram_1kbyte_1rw1r_32x256_tt_1p8V_25C.db

  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8.sp              outputs/sram_2kbyte_1rw1r_32x512.sp
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8.v               outputs/sram_2kbyte_1rw1r_32x512.v
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8.lef             outputs/sram_2kbyte_1rw1r_32x512.lef
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8_TT_1p8V_25C.lib outputs/sram_2kbyte_1rw1r_32x512_tt_1p8V_25C.lib
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8.gds             outputs/sram_2kbyte_1rw1r_32x512.gds
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8_TT_1p8V_25C.db  outputs/sram_2kbyte_1rw1r_32x512_tt_1p8V_25C.db

