flow package require MemGen
flow run /MemGen/MemoryGenerator_BuildLib {
VENDOR           Nangate
RTLTOOL          DesignCompiler
TECHNOLOGY       045nm
LIBRARY          sram_512_128_1rw1r
MODULE           sram_512_128_1rw1r
OUTPUT_DIR       ./
FILES {
  { FILENAME ./sram_512_128_1rw1r.v FILETYPE Verilog MODELTYPE generic PARSE 1 PATHTYPE copy STATICFILE 1 VHDL_LIB_MAPS work }
}
VHDLARRAYPATH    {}
WRITEDELAY       0.1
INITDELAY        1
READDELAY        0.1
VERILOGARRAYPATH {}
INPUTDELAY       0.01
TIMEUNIT         1ns
WIDTH            128
AREA             0
RDWRRESOLUTION   UNKNOWN
WRITELATENCY     1
READLATENCY      1
DEPTH            512
PARAMETERS {
  { PARAMETER DATA_WIDTH TYPE hdl IGNORE 1 MIN {} MAX {} DEFAULT 32  }
  { PARAMETER NUM_WMASKS TYPE hdl IGNORE 1 MIN {} MAX {} DEFAULT 4   }
  { PARAMETER ADDR_WIDTH TYPE hdl IGNORE 1 MIN {} MAX {} DEFAULT 9   }
  { PARAMETER RAM_DEPTH  TYPE hdl IGNORE 1 MIN {} MAX {} DEFAULT 512 }
  { PARAMETER DELAY      TYPE hdl IGNORE 1 MIN {} MAX {} DEFAULT 0   }
}
PORTS {
  { NAME port_0 MODE ReadWrite }
  { NAME port_1 MODE Read      }
}
PINMAPS {
  { PHYPIN clk0  LOGPIN CLOCK        DIRECTION in  WIDTH 1.0 PHASE 1  DEFAULT {} PORTS port_0 }
  { PHYPIN csb0  LOGPIN CHIP_SELECT  DIRECTION in  WIDTH 1.0 PHASE 0  DEFAULT {} PORTS {}     }
  { PHYPIN web0  LOGPIN WRITE_ENABLE DIRECTION in  WIDTH 1.0 PHASE 0  DEFAULT {} PORTS port_0 }
  { PHYPIN addr0 LOGPIN ADDRESS      DIRECTION in  WIDTH 9   PHASE {} DEFAULT {} PORTS port_0 }
  { PHYPIN din0  LOGPIN DATA_IN      DIRECTION in  WIDTH 128 PHASE {} DEFAULT {} PORTS port_0 }
  { PHYPIN dout0 LOGPIN DATA_OUT     DIRECTION out WIDTH 128 PHASE {} DEFAULT {} PORTS port_0 }
  { PHYPIN clk1  LOGPIN CLOCK        DIRECTION in  WIDTH 1.0 PHASE 1  DEFAULT {} PORTS port_1 }
  { PHYPIN csb1  LOGPIN CHIP_SELECT  DIRECTION in  WIDTH 1.0 PHASE 0  DEFAULT {} PORTS {}     }
  { PHYPIN addr1 LOGPIN ADDRESS      DIRECTION in  WIDTH 9   PHASE {} DEFAULT {} PORTS port_1 }
  { PHYPIN dout1 LOGPIN DATA_OUT     DIRECTION out WIDTH 128 PHASE {} DEFAULT {} PORTS port_1 }
}

}
