#=========================================================================
# OpenRAM SRAM Compiler 
#=========================================================================
# Author : Kartik Prabhu
# Date   : February 15, 2020
#

name: sram

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------

outputs:
  - sram.sp
  - sram.v
  - sram.lef
  - sram_tt_1p8V_25C.lib
  - sram_tt_1p8V_25C.db
  - sram.gds

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.sp              outputs/sram.sp
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.v               outputs/sram.v
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.lef             outputs/sram.lef
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib outputs/sram_tt_1p8V_25C.lib
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.gds             outputs/sram.gds
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db  outputs/sram_tt_1p8V_25C.db

